language: go

go:
  - '1.9'
  - '1.10'
  - '1.11'
  - tip

env:
  - VIPS_VERSION=8.3
  - VIPS_VERSION=8.4
  - VIPS_VERSION=8.5
  - VIPS_VERSION=8.6
  - VIPS_VERSION=8.7
  - VIPS_VERSION=master

matrix:
  allow_failures:
    - env: VIPS_VERSION=master

cache: apt

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libxml2-dev libfftw3-dev gobject-introspection libglib2.0-dev libwebp-dev libgif-dev gtk-doc-tools
  - wget https://github.com/libvips/libvips/archive/$VIPS_VERSION.zip
  - unzip $VIPS_VERSION.zip
  - pushd libvips-$VIPS_VERSION
  - test -f autogen.sh && ./autogen.sh || ./bootstrap.sh
  - >
    ./configure
    --prefix=/usr
    --without-python
    --without-gsf
    --without-orc
    --disable-debug
    --disable-dependency-tracking
    --disable-static
    --enable-silent-rules
    --enable-gtk-doc-html=no
    --enable-gtk-doc=no
    --enable-pyvips8=no
  - make
  - sudo make install
  - popd

script:
  - CGO_LDFLAGS_ALLOW="-s|-w" go build
